package com.example.restservice.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Set;

@Entity
@Table(name = "submissions")
public class Submission {
    @Id
    @GeneratedValue
    private Long id; //提交id

    @ManyToOne
    private Assignment assignment; //作业

    @ManyToOne
    private User user; //用户

    private LocalDateTime submitTime; //提交时间

    private Float score; //分数

    private Boolean scoreVisible; //分数是否可见

    // code

    private ProgrammingLanguage programmingLanguage;

    @ElementCollection
    @OrderColumn
    private List<String> judgeIds;

    // 与 SubmissionFile 的关系
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "submission")
    private Set<SubmissionFile> submissionFiles; //与文件的关系

    public void updateWithoutId(Submission submissionDetails) {
        if (submissionDetails.getAssignment() != null) {
            this.assignment = submissionDetails.getAssignment();
        }
        if (submissionDetails.getUser() != null) {
            this.user = submissionDetails.getUser();
        }
        if (submissionDetails.getSubmitTime() != null) {
            this.submitTime = submissionDetails.getSubmitTime();
        }
        if (submissionDetails.getScore() != null) {
            this.score = submissionDetails.getScore();
        }
        if (submissionDetails.getScoreVisible() != null) {
            this.scoreVisible = submissionDetails.getScoreVisible();
        }
    }
    /*
    Generated by AI
    AI used: Grok3
     */

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Assignment getAssignment() {
        return assignment;
    }

    public void setAssignment(Assignment assignment) {
        this.assignment = assignment;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public LocalDateTime getSubmitTime() {
        return submitTime;
    }

    public void setSubmitTime(LocalDateTime submitTime) {
        this.submitTime = submitTime;
    }

    public Float getScore() {
        return score;
    }

    public void setScore(Float score) {
        this.score = score;
    }

    public Boolean getScoreVisible() {
        return scoreVisible;
    }

    public void setScoreVisible(Boolean scoreVisible) {
        this.scoreVisible = scoreVisible;
    }

    public ProgrammingLanguage getProgrammingLanguage() {
        return programmingLanguage;
    }

    public void setProgrammingLanguage(ProgrammingLanguage programmingLanguage) {
        this.programmingLanguage = programmingLanguage;
    }

    public List<String> getJudgeIds() {
        return judgeIds;
    }

    public void setJudgeIds(List<String> judgeIds) {
        this.judgeIds = judgeIds;
    }
}