name: CI
on:
  pull_request:
    types:
      - opened
    branches:
      - 'frontend/**'
jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write app/**/*.{md,js,jsx,ts,tsx}
